name: rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - chromadb==0.4.18
    - sentence-transformers==2.2.2
    - openai==1.3.8
    - python-dotenv==1.0.0
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - httpx==0.25.2
    - pydantic==2.5.0
    - markdown==3.5.1
    - numpy==1.24.3
